version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: lab2_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: lab2_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: stacia
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
